arexp:
  build: .
  ports:
    - "3030:3000"
  environment:
    - VIRTUAL_HOST=aretemp.benjick.se
    - VIRTUAL_PORT=3000
    - LETSENCRYPT_HOST=aretemp.benjick.se
    - LETSENCRYPT_EMAIL=benjick@dumfan.net
