arexp:
  build: .
  ports:
    - "3030:3000"
  environment:
    - VIRTUAL_HOST=animalrealityexposed.com,www.animalrealityexposed.com
    - VIRTUAL_PORT=3000
    - LETSENCRYPT_HOST=animalrealityexposed.com,www.animalrealityexposed.com
    - LETSENCRYPT_EMAIL=benjick@dumfan.net
